import { useEffect, useState } from "react";
import { useTranslation } from "react-i18next";
import { useAuth } from "../auth/AuthContext.jsx";
import { createCategory, createService, getLeadScoringSettings, listCategories, listServices, updateCategory, updateLeadScoringSettings, updateService } from "../services/business.js";

const categoryBlank={name_ru:"",name_en:"",name_es:"",target_hourly_rate:"",target_effort:""};
const serviceBlank={name_ru:"",name_en:"",name_es:"",category_id:""};
export default function BusinessSettingsPage(){
 const {t,i18n}=useTranslation();const {accessToken}=useAuth();const [data,setData]=useState({categories:[],services:[],settings:null}),[modal,setModal]=useState(null),[state,setState]=useState("loading"),[error,setError]=useState("");const lang=i18n.resolvedLanguage||"ru";const label=x=>x[`name_${lang}`]||x.name_ru;
 const load=async()=>{setState("loading");try{const [categories,services,settings]=await Promise.all([listCategories(accessToken),listServices(accessToken),getLeadScoringSettings(accessToken)]);setData({categories,services,settings});setState("ready");}catch{setState("error");}};useEffect(()=>{load();},[accessToken]);
 const save=async(fn)=>{setError("");try{await fn();setModal(null);await load();}catch{setError(t("business.mutationError"));}};
 const modalFields=(isService)=> <>{["name_ru","name_en","name_es"].map(k=><label className="field" key={k}><span>{t(`business.fields.${k}`)}</span><input required value={modal.form[k]} onChange={e=>setModal(m=>({...m,form:{...m.form,[k]:e.target.value}}))}/></label>)}{isService?<label className="field"><span>{t("business.category")}</span><select value={modal.form.category_id} onChange={e=>setModal(m=>({...m,form:{...m.form,category_id:e.target.value}}))}>{data.categories.filter(x=>x.is_active||x.id===modal.form.category_id).map(x=><option key={x.id} value={x.id}>{label(x)}</option>)}</select></label>:["target_hourly_rate","target_effort"].map(k=><label className="field" key={k}><span>{t(`business.fields.${k}`)}</span><input required type="number" min="0.01" step="0.01" value={modal.form[k]} onChange={e=>setModal(m=>({...m,form:{...m.form,[k]:e.target.value}}))}/></label>)}</>;
 if(state!=="ready")return <div className="state-panel"><p>{t(state==="loading"?"business.loading":"business.error")}</p></div>;
 const settings=data.settings; const setSetting=(k,v)=>setData(d=>({...d,settings:{...d.settings,[k]:v}}));
 return <><section className="page-header"><div><p className="eyebrow">{t("business.eyebrow")}</p><h1>{t("business.title")}</h1><p>{t("business.subtitle")}</p></div></section><div className="settings-grid">
 <section className="content-surface settings-card settings-card--wide"><h2>{t("business.scoring")}</h2><form className="compact-form compact-form--row" onSubmit={e=>{e.preventDefault();save(()=>updateLeadScoringSettings(accessToken,settings));}}>{["service_fit_weight","commercial_value_weight","lead_quality_weight","feasibility_weight"].map(k=><label className="field" key={k}><span>{t(`business.fields.${k}`)}</span><input type="number" value={settings[k]} onChange={e=>setSetting(k,Number(e.target.value))}/></label>)}<div className="field field--full"><span>{t("business.scale")}</span><div className="scale-fields">{settings.commercial_value_scale.map((p,i)=><span key={i}><input type="number" step="0.01" value={p.ratio} onChange={e=>setSetting("commercial_value_scale",settings.commercial_value_scale.map((x,n)=>n===i?{...x,ratio:e.target.value}:x))}/> → <input type="number" value={p.score} onChange={e=>setSetting("commercial_value_scale",settings.commercial_value_scale.map((x,n)=>n===i?{...x,score:Number(e.target.value)}:x))}/></span>)}</div></div><button className="primary-button">{t("common.save")}</button></form></section>
 {[['categories',false],['services',true]].map(([kind,isService])=><section className="content-surface settings-card" key={kind}><div className="settings-section-header"><h2>{t(`business.${kind}`)}</h2><button className="primary-button" onClick={()=>setModal({kind,form:isService?{...serviceBlank,category_id:data.categories.find(x=>x.is_active)?.id||""}:{...categoryBlank}})}>＋ {t(isService?"business.addService":"business.addCategory")}</button></div><div className="settings-list settings-list--rows">{data[kind].map(item=><button className="settings-list-row" key={item.id} onClick={()=>setModal({kind,form:{...item}})}><span>{label(item)}</span><span aria-hidden="true">›</span></button>)}</div></section>)}
 </div>{modal&&<div className="modal-backdrop"><section className="client-modal"><button className="icon-button" onClick={()=>setModal(null)}>×</button><h2>{t(`business.${modal.kind}`)}</h2><form className="compact-form" onSubmit={e=>{e.preventDefault();const service=modal.kind==="services",f=modal.form;const payload=service?{name_ru:f.name_ru,name_en:f.name_en,name_es:f.name_es,category_id:f.category_id}:{name_ru:f.name_ru,name_en:f.name_en,name_es:f.name_es,target_hourly_rate:f.target_hourly_rate,target_effort:f.target_effort};save(()=>f.id?(service?updateService(accessToken,f.id,payload):updateCategory(accessToken,f.id,payload)):(service?createService(accessToken,payload):createCategory(accessToken,payload)));}}>{modalFields(modal.kind==="services")}{error&&<p className="form-error">{error}</p>}<button className="primary-button">{t("common.save")}</button>{modal.form.id&&<button type="button" className="secondary-button" onClick={()=>save(()=>modal.kind==="services"?updateService(accessToken,modal.form.id,{is_active:!modal.form.is_active}):updateCategory(accessToken,modal.form.id,{is_active:!modal.form.is_active}))}>{t(`business.${modal.form.is_active?"deactivate":"activate"}`)}</button>}</form></section></div>}</>;
}
