import { useCallback, useEffect, useState } from "react";
import { useTranslation } from "react-i18next";
import { useAuth } from "../auth/AuthContext.jsx";
import { listClients } from "../services/clients.js";
import { listDeals } from "../services/deals.js";
import { bulkDeleteInboxMessages, linkInboxMessage, listInboxMessages } from "../services/inbox.js";

function sender(message, t) { if (message.channel === "EMAIL") return message.sender_identifier; const name = [message.sender_first_name, message.sender_last_name].filter(Boolean).join(" "); const user = message.sender_username ? `@${message.sender_username}` : ""; return name ? (user ? `${name} (${user})` : name) : (user || t("p1_7a.telegramFallback")); }

export default function InboxPage() {
  const { t } = useTranslation(); const { accessToken, user } = useAuth();
  const [messages,setMessages]=useState([]),[clients,setClients]=useState([]),[deals,setDeals]=useState([]),[selection,setSelection]=useState({}),[checked,setChecked]=useState({}),[channel,setChannel]=useState(""),[state,setState]=useState("loading"),[error,setError]=useState("");
  const load=useCallback(()=>{const c=new AbortController();setState("loading");Promise.all([listInboxMessages(accessToken,c.signal,channel),listClients(accessToken,{limit:100,offset:0},c.signal),listDeals(accessToken,{limit:100,offset:0},c.signal)]).then(([m,cl,d])=>{setMessages(m);setClients(cl);setDeals(d);setChecked({});setState("ready");}).catch(()=>setState("error"));return c;},[accessToken,channel]); useEffect(()=>{const c=load();return()=>c.abort();},[load]);
  async function link(id){const v=selection[id]||{};if(!v.clientId&&!v.dealId){setError(t("inbox.errors.clientRequired"));return;}try{await linkInboxMessage(accessToken,id,v.clientId||null,v.dealId||null);setMessages(x=>x.filter(m=>m.id!==id));}catch{setError(t("inbox.errors.link"));}}
  async function remove(){const ids=Object.keys(checked).filter(id=>checked[id]);if(!ids.length||!window.confirm(t("p1_7.confirmDelete",{count:ids.length})))return;try{await bulkDeleteInboxMessages(accessToken,ids);setMessages(x=>x.filter(m=>!checked[m.id]));setChecked({});}catch{setError(t("p1_7.deleteError"));}}
  return <><section className="page-header"><div><p className="eyebrow">{t("crm.navigation.inbox")}</p><h1>{t("inbox.title")}</h1><p>{t("inbox.subtitle")}</p></div></section><section className="content-surface inbox-surface"><div className="button-group"><button className="secondary-button" onClick={()=>setChannel("")}>{t("p1_7.all")}</button><button className="secondary-button" onClick={()=>setChannel("EMAIL")}>Email</button><button className="secondary-button" onClick={()=>setChannel("TELEGRAM")}>Telegram</button>{user.role==="ADMIN"&&<button className="primary-button" onClick={remove}>{t("p1_7.deleteSelected",{count:Object.values(checked).filter(Boolean).length})}</button>}</div>{state==="loading"&&<p>{t("inbox.loading")}</p>}{state==="error"&&<p className="form-error">{error||t("inbox.errors.load")}</p>}{state==="ready"&&<div className="inbox-list">{messages.map(m=>{const v=selection[m.id]||{};return <article className="inbox-message" key={m.id}>{user.role==="ADMIN"&&<input type="checkbox" checked={!!checked[m.id]} onChange={e=>setChecked(x=>({...x,[m.id]:e.target.checked}))}/>}<p className="inbox-sender">{t("p1_7a.from")}: {sender(m,t)}</p>{m.channel==="EMAIL"&&m.subject&&<p className="inbox-subject">{t("p1_7a.subject")}: {m.subject}</p>}<p className="inbox-message__content">{m.content}</p><label className="field"><span>{t("inbox.selectDeal")}</span><select value={v.dealId||""} onChange={e=>setSelection(x=>({...x,[m.id]:{dealId:e.target.value}}))}><option value="">{t("inbox.dealPlaceholder")}</option>{deals.map(d=><option key={d.id} value={d.id}>{d.name} — {clients.find(c=>c.id===d.client_id)?.name||"—"}</option>)}</select></label><label className="field"><span>{t("inbox.selectClient")}</span><select value={v.clientId||""} disabled={!!v.dealId} onChange={e=>setSelection(x=>({...x,[m.id]:{clientId:e.target.value}}))}><option value="">{t("inbox.clientPlaceholder")}</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><button className="primary-button" onClick={()=>link(m.id)}>{t("inbox.link")}</button></article>;})}</div>}</section></>;
}
