import { useCallback, useEffect, useState } from "react";
import { useTranslation } from "react-i18next";
import { useAuth } from "../auth/AuthContext.jsx";
import { listClients } from "../services/clients.js";
import { linkInboxMessage, listInboxMessages } from "../services/inbox.js";

function formatDate(value, locale) { return new Intl.DateTimeFormat(locale, { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)); }

export default function InboxPage() {
  const { t, i18n } = useTranslation(); const { accessToken } = useAuth();
  const [messages, setMessages] = useState([]); const [clients, setClients] = useState([]); const [selection, setSelection] = useState({}); const [state, setState] = useState("loading"); const [error, setError] = useState(""); const [saving, setSaving] = useState("");
  const load = useCallback(() => { const controller = new AbortController(); setState("loading"); setError(""); Promise.all([listInboxMessages(accessToken, controller.signal), listClients(accessToken, { limit: 100, offset: 0 }, controller.signal)]).then(([nextMessages, nextClients]) => { setMessages(nextMessages); setClients(nextClients); setState("ready"); }).catch((nextError) => { if (nextError.name !== "AbortError") { setError(t("inbox.errors.load")); setState("error"); } }); return controller; }, [accessToken, t]);
  useEffect(() => { const controller = load(); return () => controller.abort(); }, [load]);
  async function link(messageId) { const clientId = selection[messageId]; if (!clientId) { setError(t("inbox.errors.clientRequired")); return; } setSaving(messageId); setError(""); try { await linkInboxMessage(accessToken, messageId, clientId); setMessages((items) => items.filter((message) => message.id !== messageId)); } catch { setError(t("inbox.errors.link")); } finally { setSaving(""); } }
  const locale = i18n.resolvedLanguage ?? "ru";
  return <><section className="page-header"><div><p className="eyebrow">{t("crm.navigation.inbox")}</p><h1>{t("inbox.title")}</h1><p>{t("inbox.subtitle")}</p></div></section><section className="content-surface inbox-surface" aria-live="polite">{state === "loading" && <div className="state-panel"><span className="loading-spinner" /><p>{t("inbox.loading")}</p></div>}{state === "error" && <div className="state-panel"><p className="form-error">{error}</p><button className="secondary-button" type="button" onClick={load}>{t("common.retry")}</button></div>}{state === "ready" && messages.length === 0 && <div className="state-panel"><h2>{t("inbox.empty.title")}</h2><p>{t("inbox.empty.description")}</p></div>}{state === "ready" && messages.length > 0 && <div className="inbox-list">{messages.map((message) => <article className="inbox-message" data-testid={`inbox-message-${message.id}`} key={message.id}><div className="inbox-message__meta"><strong>{t(`inbox.providers.${message.provider}`)}</strong><span>{t(`communications.channels.${message.channel}`)}</span><span>{message.sender_identifier}</span><time dateTime={message.occurred_at}>{formatDate(message.occurred_at, locale)}</time></div>{message.subject && <h2>{message.subject}</h2>}<p className="inbox-message__content">{message.content}</p><div className="inbox-message__action"><label className="field"><span>{t("inbox.selectClient")}</span><select data-testid={`inbox-client-select-${message.id}`} value={selection[message.id] ?? ""} onChange={(event) => setSelection((previous) => ({ ...previous, [message.id]: event.target.value }))} disabled={saving === message.id}><option value="">{t("inbox.clientPlaceholder")}</option>{clients.map((client) => <option value={client.id} key={client.id}>{client.name}</option>)}</select></label><button data-testid={`inbox-link-${message.id}`} className="primary-button" type="button" onClick={() => link(message.id)} disabled={saving === message.id}>{t(saving === message.id ? "common.saving" : "inbox.link")}</button></div></article>)}</div>}{state === "ready" && error && <p className="form-error inbox-error" role="alert">{error}</p>}</section></>;
}
