import { useEffect, useState } from "react";
import { useTranslation } from "react-i18next";

import { useAuth } from "../auth/AuthContext.jsx";
import { connectGoogle, disconnectGoogle, listIntegrationConnections, reconnectGoogle, syncGmailInbound, validateTelegram } from "../services/integrations.js";

const SAFE_ERROR_CODES = new Set(["AUTH_REQUIRED", "INVALID_CONFIGURATION", "PERMISSION_DENIED", "INVALID_RECIPIENT", "RATE_LIMITED", "PROVIDER_UNAVAILABLE", "PROVIDER_ERROR"]);
const formatDateTime = (value, locale) => new Intl.DateTimeFormat(locale, { dateStyle: "medium", timeStyle: "short" }).format(new Date(value));
const safeErrorLabel = (t, code) => SAFE_ERROR_CODES.has(code) ? t(`integrations.errorCodes.${code}`) : t("integrations.errorCodes.generic");

export default function IntegrationSettingsPage() {
  const { t, i18n } = useTranslation(); const { accessToken } = useAuth();
  const [items, setItems] = useState([]); const [state, setState] = useState("loading"); const [action, setAction] = useState(null); const [actionError, setActionError] = useState(false); const [callback, setCallback] = useState(null);
  const locale = i18n.resolvedLanguage ?? "ru";
  const load = async () => { setState("loading"); try { setItems(await listIntegrationConnections(accessToken)); setState("ready"); } catch { setState("error"); } };
  useEffect(() => { const outcome = new URLSearchParams(window.location.search).get("google_oauth"); if (outcome) { setCallback(outcome); window.history.replaceState({}, "", window.location.pathname); } load(); }, [accessToken]);
  const runGoogleAction = async (kind) => { setAction(kind); setActionError(false); try { if (kind === "disconnect") { await disconnectGoogle(accessToken); await load(); return; } const result = kind === "connect" ? await connectGoogle(accessToken) : await reconnectGoogle(accessToken); window.location.assign(result.authorization_url); } catch { setActionError(true); } finally { setAction(null); } };
  const runInboundSync = async () => { setAction("sync"); setActionError(false); try { await syncGmailInbound(accessToken); await load(); } catch { setActionError(true); } finally { setAction(null); } };
  const runTelegramValidation = async () => { setAction("telegram"); setActionError(false); try { await validateTelegram(accessToken); await load(); } catch { setActionError(true); } finally { setAction(null); } };
  function detail(item) { if (item.provider === "WHATSAPP") return <p className="readonly-note">{t("integrations.whatsapp.deferred")}</p>; return <><small>{item.external_account_email || item.external_account_id || (item.status === "CONNECTED" ? t("integrations.connectedNoAccount") : t("integrations.notConfigured"))}</small>{item.provider === "GOOGLE_CALENDAR" && <p className="readonly-note">{t("integrations.calendar.reusesGoogle")}</p>}{item.last_success_at && <p className="readonly-note">{t("integrations.lastSuccess", { value: formatDateTime(item.last_success_at, locale) })}</p>}{item.provider === "GMAIL" && item.last_inbound_sync_at && <p className="readonly-note">{t("integrations.inbound.lastSuccess", { value: formatDateTime(item.last_inbound_sync_at, locale) })}</p>}{item.status === "ERROR" && <p className="form-error">{safeErrorLabel(t, item.last_error_code)}</p>}{item.provider === "GMAIL" && item.inbound_sync_status === "ERROR" && <p className="form-error">{safeErrorLabel(t, item.inbound_sync_error_code)}</p>}</>; }
  function actions(item) { if (item.provider === "WHATSAPP" || item.provider === "GOOGLE_CALENDAR") return null; if (item.provider === "TELEGRAM") return <div className="form-actions"><button className="primary-button" disabled={Boolean(action) || item.status === "CONNECTING"} onClick={runTelegramValidation}>{action === "telegram" ? t("integrations.telegram.validating") : t("integrations.telegram.validate")}</button></div>; return <div className="form-actions">{item.inbound_sync_status === "RUNNING" && <small className="status-note">{t("integrations.inbound.running")}</small>}{item.status === "CONNECTED" && <button className="secondary-button" disabled={Boolean(action) || item.inbound_sync_status === "RUNNING"} onClick={runInboundSync}>{action === "sync" ? t("integrations.inbound.running") : t("integrations.inbound.sync")}</button>}{item.status === "DISCONNECTED" && <button className="primary-button" disabled={Boolean(action)} onClick={() => runGoogleAction("connect")}>{action === "connect" ? t("integrations.oauth.opening") : t("integrations.oauth.connect")}</button>}{item.status === "ERROR" && <button className="primary-button" disabled={Boolean(action)} onClick={() => runGoogleAction("reconnect")}>{action === "reconnect" ? t("integrations.oauth.opening") : t("integrations.oauth.reconnect")}</button>}{item.status === "CONNECTED" && <><button className="secondary-button" disabled={Boolean(action)} onClick={() => runGoogleAction("reconnect")}>{action === "reconnect" ? t("integrations.oauth.opening") : t("integrations.oauth.reconnect")}</button><button className="secondary-button" disabled={Boolean(action)} onClick={() => runGoogleAction("disconnect")}>{action === "disconnect" ? t("integrations.oauth.disconnecting") : t("integrations.oauth.disconnect")}</button></>}</div>; }
  return <><section className="page-header"><div><p className="eyebrow">CRM</p><h1>{t("integrations.title")}</h1><p>{t("integrations.subtitle")}</p></div></section>{callback && <p className={callback === "success" ? "status-note" : "form-error"}>{t(`integrations.oauth.${callback}`)}</p>}{actionError && <p className="form-error">{t("integrations.oauth.actionError")}</p>}{state === "loading" ? <div className="state-panel"><span className="loading-spinner"/><p>{t("integrations.loading")}</p></div> : state === "error" ? <div className="state-panel"><p className="form-error">{t("integrations.error")}</p><button className="secondary-button" onClick={load}>{t("common.retry")}</button></div> : <section className="settings-grid">{items.map((item) => <article className="content-surface settings-card" key={item.provider} data-testid={`integration-card-${item.provider}`}><h2>{t(`integrations.providers.${item.provider}`)}</h2><p className="status-note">{item.provider === "WHATSAPP" ? t("integrations.whatsapp.status") : t(`integrations.status.${item.status}`)}</p>{detail(item)}{actions(item)}</article>)}</section>}</>;
}
