import { useEffect, useState } from "react";
import { useTranslation } from "react-i18next";

import { useAuth } from "../auth/AuthContext.jsx";
import { connectGoogle, disconnectGoogle, listIntegrationConnections, reconnectGoogle, syncGmailInbound, validateTelegram } from "../services/integrations.js";

export default function IntegrationSettingsPage() {
  const { t } = useTranslation();
  const { accessToken } = useAuth();
  const [items, setItems] = useState([]);
  const [state, setState] = useState("loading");
  const [action, setAction] = useState(null);
  const [actionError, setActionError] = useState(false);
  const [callback, setCallback] = useState(null);
  const load = async () => { setState("loading"); try { setItems(await listIntegrationConnections(accessToken)); setState("ready"); } catch { setState("error"); } };
  useEffect(() => { const outcome = new URLSearchParams(window.location.search).get("google_oauth"); if (outcome) { setCallback(outcome); window.history.replaceState({}, "", window.location.pathname); } load(); }, [accessToken]);
  const runGoogleAction = async (kind) => { setAction(kind); setActionError(false); try { if (kind === "disconnect") { await disconnectGoogle(accessToken); await load(); return; } const result = kind === "connect" ? await connectGoogle(accessToken) : await reconnectGoogle(accessToken); window.location.assign(result.authorization_url); } catch { setActionError(true); } finally { setAction(null); } };
  const runInboundSync = async () => { setAction("sync"); setActionError(false); try { await syncGmailInbound(accessToken); await load(); } catch { setActionError(true); } finally { setAction(null); } };
  const runTelegramValidation = async () => { setAction("telegram"); setActionError(false); try { await validateTelegram(accessToken); await load(); } catch { setActionError(true); } finally { setAction(null); } };
  return <><section className="page-header"><div><p className="eyebrow">CRM</p><h1>{t("integrations.title")}</h1><p>{t("integrations.subtitle")}</p></div></section>{callback && <p className={callback === "success" ? "status-note" : "form-error"}>{t(`integrations.oauth.${callback}`)}</p>}{actionError && <p className="form-error">{t("integrations.oauth.actionError")}</p>}{state === "loading" ? <div className="state-panel"><span className="loading-spinner"/><p>{t("integrations.loading")}</p></div> : state === "error" ? <div className="state-panel"><p className="form-error">{t("integrations.error")}</p><button className="secondary-button" onClick={load}>{t("common.retry")}</button></div> : <section className="settings-grid">{items.map((item) => <article className="content-surface settings-card" key={item.provider}><h2>{t(`integrations.providers.${item.provider}`)}</h2><p className="status-note">{t(`integrations.status.${item.status}`)}</p><small>{item.external_account_email || item.external_account_id || (item.status === "CONNECTED" ? t("integrations.connectedNoAccount") : t("integrations.notConfigured"))}</small>{item.provider === "TELEGRAM" && <div className="form-actions"><button className="primary-button" disabled={Boolean(action)} onClick={runTelegramValidation}>{action === "telegram" ? t("integrations.telegram.validating") : t("integrations.telegram.validate")}</button></div>}{item.provider === "GMAIL" && <div className="form-actions">{item.inbound_sync_status === "RUNNING" && <small className="status-note">{t("integrations.inbound.running")}</small>}{item.inbound_sync_status === "ERROR" && <small className="form-error">{t("integrations.inbound.error")}</small>}{item.status === "CONNECTED" && <button className="secondary-button" disabled={Boolean(action)} onClick={runInboundSync}>{action === "sync" ? t("integrations.inbound.running") : t("integrations.inbound.sync")}</button>}{item.status === "DISCONNECTED" ? <button className="primary-button" disabled={Boolean(action)} onClick={() => runGoogleAction("connect")}>{action === "connect" ? t("integrations.oauth.opening") : t("integrations.oauth.connect")}</button> : item.status === "ERROR" ? <button className="primary-button" disabled={Boolean(action)} onClick={() => runGoogleAction("reconnect")}>{action === "reconnect" ? t("integrations.oauth.opening") : t("integrations.oauth.reconnect")}</button> : <><button className="secondary-button" disabled={Boolean(action)} onClick={() => runGoogleAction("reconnect")}>{action === "reconnect" ? t("integrations.oauth.opening") : t("integrations.oauth.reconnect")}</button><button className="secondary-button" disabled={Boolean(action)} onClick={() => runGoogleAction("disconnect")}>{action === "disconnect" ? t("integrations.oauth.disconnecting") : t("integrations.oauth.disconnect")}</button></>}</div>}</article>)}</section>}</>;
}
