import { requireApiBaseUrl } from "./api.js";
export async function listIntegrationConnections(token, signal) { const response=await fetch(`${requireApiBaseUrl()}/settings/integrations`,{signal,headers:{Authorization:`Bearer ${token}`}}); const body=await response.json().catch(()=>null); if(!response.ok) throw new Error(body?.detail||"Integration settings request failed"); return body; }
async function googleAction(token, path) { const response=await fetch(`${requireApiBaseUrl()}/settings/integrations/google/${path}`,{method:"POST",headers:{Authorization:`Bearer ${token}`}}); const body=await response.json().catch(()=>null); if(!response.ok) throw new Error(body?.detail||"Google integration action failed"); return body; }
export function connectGoogle(token) { return googleAction(token,"connect"); }
export function reconnectGoogle(token) { return googleAction(token,"reconnect"); }
export function disconnectGoogle(token) { return googleAction(token,"disconnect"); }
export async function syncGmailInbound(token) { const response=await fetch(`${requireApiBaseUrl()}/settings/integrations/gmail/sync`,{method:"POST",headers:{Authorization:`Bearer ${token}`}}); const body=await response.json().catch(()=>null); if(!response.ok) throw new Error(body?.detail||"Gmail synchronization request failed"); return body; }
export async function validateTelegram(token) { const response=await fetch(`${requireApiBaseUrl()}/settings/integrations/telegram/validate`,{method:"POST",headers:{Authorization:`Bearer ${token}`}}); const body=await response.json().catch(()=>null); if(!response.ok) throw new Error(body?.detail||"Telegram configuration request failed"); return body; }
export async function sendTelegram(token, payload, idempotencyKey) { const response=await fetch(`${requireApiBaseUrl()}/settings/integrations/telegram/messages`,{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json","Idempotency-Key":idempotencyKey},body:JSON.stringify(payload)}); const body=await response.json().catch(()=>null); if(!response.ok) throw new Error(body?.detail||"Telegram send failed"); return body; }
export async function getTelegramAvailability(token) { const response=await fetch(`${requireApiBaseUrl()}/settings/integrations/telegram/availability`,{headers:{Authorization:`Bearer ${token}`}}); const body=await response.json().catch(()=>null); if(!response.ok) throw new Error(body?.detail||"Telegram availability request failed"); return body; }
